name: Push and Deploy Serverless function
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Yandex Cloud CLI tool
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Setup YCloud 
        run: |
          ~/yandex-cloud/bin/yc config set token ${{ secrets.YACLOUD_TOKEN }}
          CLOUD_ID=$(~/yandex-cloud/bin/yc resource-manager cloud get --name ${{secrets.CLOUD_NAME}} | awk '/^id:/ {print $2}')
          FOLDER_ID=$(~/yandex-cloud/bin/yc resource-manager folder get --name ${{ secrets.YACLOUD_FOLDER_NAME }})
          ~/yandex-cloud/bin/yc config set folder-id $FOLDER_ID
          ~/yandex-cloud/bin/yc config set cloud-id $CLOUD_ID
      - name: Create source archive
        run: zip -r deploy-archive.zip ./src
      - name: Deploy cloud function
        run: |
          ~/yandex-cloud/bin/yc serverless function version create --function-name=${{ secrets.FUNCTION_NAME}} --runtime python311 --entrypoint main.handler --memory 128m --execution-timeout 5s --source-path ./deploy-archive.zip