name: Push and Deploy Serverless function
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v2
      with:
        token: ${{ secrets.TOKEN }}
        function_id: 'd4elaoh7cqo786mhqssh'
        runtime: 'python311'
        memory: '128'
        entrypoint: 'main.handler'
        environment: DEBUG=True,COUNT=1,TOKEN=${{secrets.TGBOTTOKEN}}
        source: 'src/'
        # exclude: 